name = "appcalculusworker"
main = "src/backend.js"
compatibility_date = "2025-08-24"

[[d1_databases]]
"d1_databases" = [{ "binding": "DB", "database_name": "appcalculusdata", "database_id": "5fa138c8-d865-4f23-bca0-05f40cd174c3" }]